version: "3"
services:
  mariadb:
    image: mariadb
    build: requirements/mariadb
    container_name: mariadb
    ports:
      - "3306"
    volumes:
        - wp-db:/var/lib/mysql
    networks:
      - mynetwork
    env_file:
      - .env
    restart: always

  wordpress:
    image: wordpress
    build: requirements/wordpress
    container_name: wordpress
    ports:
      - "9000"
    volumes:
        - wp-files:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    networks:
      - mynetwork

  nginx:
    image: nginx
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
        - wp-files:/var/www/html
    depends_on:
      - mariadb
      - wordpress
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
volumes:
  wp-db:
  wp-files:
