---
- hosts: server
  become: true
  vars_files:
    - vars.yml
  tasks:

  - name: run services
    include_role:
      name: '{{ item }}'
    with_items:
      # - "common"
      # - "db"
      - "wordpress"
      # - "webserver"



      # mysqladmin -h localhost -u root -ptoor ping