---
- hosts: server
  become: true
  vars_files:
    - vars.yml
  tasks:
  - name: Check if variables exist and are not null
      assert:
        that:
          - app_dir is defined
          - app_dir is not none
          - database_user is defined
          - database_user is not none
          - database_password is defined
          - database_password is not none
          - database_name is defined
          - database_name is not none
          - wp_user is defined
          - wp_user is not none
          - wp_password is defined
          - wp_password is not none
          - wp_site_name is defined
          - wp_site_name is not none
          - wp_email is defined
          - wp_email is not none
        fail_msg: "One or more variables are not defined or are null"

  - name: run services
    include_role:
      name: '{{ item }}'
    with_items:
      - "common"
      - "db"
      - "wordpress"
      # - "webserver"



      # mysqladmin -h localhost -u root -ptoor ping