---
- hosts: server
  become: true
  vars_files:
    - vars.yml
  tasks:
  - name: Check if variables exist and are not null
    assert:
      that:
          - app_dir is defined
          - app_dir is not none
          - database_user is defined
          - database_user is not none
          - database_password is defined
          - database_password is not none
          - database_name is defined
          - database_name is not none
          - wp_user is defined
          - wp_user is not none
          - wp_password is defined
          - wp_password is not none
          - wp_site_name is defined
          - wp_site_name is not none
          - wp_email is defined
          - wp_email is not none
      fail_msg: "One or more variables are not defined or are null"

  - name: run services
    include_role:
      name: '{{ item }}'
      apply:
        tags:
          - install
    with_items:
      - "common"
      - "db"
      - "wordpress"
      - "webserver"
      - "phpmyadmin"
    tags:
      - install
      - all
      


      # mysqladmin -h localhost -u root -ptoor ping
  - name: docker-compose down
    shell: |
        docker-compose down  
    args:
      chdir: "{{ app_dir }}"
    tags:
      - delete
    ignore_errors: true

  - name: remove services images
    shell: |
        docker rmi $(docker images -aq) 
    args:
      chdir: "{{ app_dir }}"
    tags:
      - delete
    ignore_errors: true

  - name: delete services volumes
    shell: |
        docker volume rm $(docker volume ls -q) 
    args:
      chdir: "{{ app_dir }}"
    tags:
      - delete
    ignore_errors: true

  - name: delete all component
    shell: |
        rm -fr {{ app_dir }}/*
    args:
      chdir: "{{ app_dir }}"
    ignore_errors: true
    tags:
      - delete