---
- name: download wordpress
  shell: |
      docker-compose -f docker-compose.yml exec wordpress \
       sh -c "/wp --allow-root core download"
  args:
    chdir: "{{ app_dir }}"
  ignore_errors: true

- name: generate wp-config.php
  shell: |
      docker-compose -f docker-compose.yml exec wordpress \
       sh -c "/wp --allow-root config create \
        --dbuser={{ database_user }} \
        --dbpass={{ database_password }} \
        --dbhost=mariadb \
        --dbname={{ database_name }} \
        --skip-check --extra-php <<PHP
           define('WP_SITEURL', 'https://{{ hostvars[inventory_hostname]['ansible_host'] }}');
           "
  args:
    chdir: "{{ app_dir }}"
  ignore_errors: true

- name: generate wordpress site
  shell: |
    docker-compose -f docker-compose.yml exec wordpress \
     sh -c "/wp --allow-root core install \
      --url={{ hostvars[inventory_hostname]['ansible_host'] }} \
      --title={{ wp_site_name }} \
      --admin_user={{ wp_user }} \
      --admin_password={{ wp_password }} \
      --admin_email={{ wp_email }} "
  args:
    chdir: "{{ app_dir }}"