---
- name: run service
  shell: "docker-compose -f docker-compose.yml up -d mariadb "
  args:
    chdir: "{{ app_dir }}"

- name: wait for db container
  retries: -1
  delay: 5
  shell: |
      docker-compose -f docker-compose.yml exec mariadb \
       sh -c 'mysqladmin ping'
  args:
    chdir: "{{ app_dir }}"
  register: mysql_alive
  until: mysql_alive.rc == 0

- name: create db
  shell: |
      docker-compose -f docker-compose.yml exec -u root mariadb \
       sh -c 'mysql -e "CREATE DATABASE {{ database_name }};"'
  args:
    chdir: "{{ app_dir }}"
  ignore_errors: true

- name: create user 
  shell: |
      docker-compose -f docker-compose.yml exec -u root mariadb \
       sh -c "mysql -e \"CREATE USER '{{ database_user }}'@'%' IDENTIFIED BY '{{ database_password}}';\""
  args:
    chdir: "{{ app_dir }}"
  ignore_errors: true

- name: grant user privileges to db
  shell: |
      docker-compose -f docker-compose.yml exec -u root mariadb \
       sh -c "mysql -e \"GRANT ALL PRIVILEGES ON {{ database_name }}.* TO '{{ database_user }}'@'%';\"" 
  args:
    chdir: "{{ app_dir }}"
